### ISSUE TITLE
Choidojur 2021 error

### ISSUE THREAD

**Issue by Andreoxcz** [rajkosto/ChoiDujour#23]
ChoiDujour 1.2.2b by rajkosto and modified by D3fau4 and Kronos2308
uses hactool by SciresM (https://github.com/SciresM/hactool)
visit https://switchtools.sshnuke.net for updates and more Switch stuff!
visit https://github.com/StarDustCFW/ChoiDujour for more updates

Using source firmware files from folder fw
Found 106 meta and 112 data NCAs in C:\Users\andre\Desktop\Downloads\Restaurar\ChoiDujour\fw
Package contains 'NX' firmware version '6.2.0' (6.2.0.0) = NintendoSDK Firmware for NX 6.2.0-1.0(hash : 921f86701e69af7ac02712e24abf18a666c2b5fb)
Using TitleID 010000000000081b for Normal firmware package
Using TitleID 010000000000081c for SAFE firmware package
Decompressing FS.kip1 from TitleID 010000000000081b hash 330553f6b5fb55c4c2d7b736240276b3
Making a request to URL http://choidujour-reloaded.tk/firmware/fs_patches.json
Traceback (most recent call last):
  File "ChoiDujour.py", line 658, in <module>
  File "ChoiDujour.py", line 175, in fetch_url_bytes
  File "urllib2.py", line 154, in urlopen
  File "urllib2.py", line 435, in open
  File "urllib2.py", line 548, in http_response
  File "urllib2.py", line 473, in error
  File "urllib2.py", line 407, in _call_chain
  File "urllib2.py", line 556, in http_error_default
urllib2.HTTPError: HTTP Error 424:
[8604] Failed to execute script ChoiDujour

**Comment by Andreoxcz** [comment]
Please Help!!!

**Comment by pereic11** [comment]
hi, im idem error, you can resolve?
