### ISSUE TITLE
Im getting this error

### ISSUE THREAD

**Issue by Paradoxica6** [rajkosto/ChoiDujour#5]
ChoiDujour 1.1.0 by rajkosto
uses hactool by SciresM (https://github.com/SciresM/hactool)
visit https://switchtools.sshnuke.net for updates and more Switch stuff!

Using source firmware files from folder NintendoSDK Firmware for NX 5.1.0-3.0
Found 105 meta and 104 data NCAs in D:\Downloads\ChoiDujour110\NintendoSDK Firmware for NX 5.1.0-3.0
Package contains 'NX' firmware version '5.1.0' (5.1.0.0) = NintendoSDK Firmware for NX 5.1.0-3.0(hash : 23f9df53e25709d756e0c76effcb2473bd3447dd)
Using TitleID 010000000000081b for Normal firmware package
Using TitleID 010000000000081c for SAFE firmware package
Traceback (most recent call last):
  File "ChoiDujour.py", line 631, in <module>
  File "ChoiDujour.py", line 222, in call_hactool
Exception: Failed to decrypt PK21! Is correct key present?. Code: 1
[12276] Failed to execute script ChoiDujour

**Comment by gpoumarat** [comment]
Do you find an issue?
